name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: cargo test --verbose
      - name: compile release
        run: cargo build --release
      - name: upload release
        uses: actions/upload-artifact@v2
        with:
        # make a release for each OS
          name: release-${{ matrix.os }}
          path: target/release/${{ matrix.os }}
  release:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - name: download release
        uses: actions/download-artifact@v2
        with:
          name: release-${{ matrix.os }}
      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/${{ matrix.os }}
          draft: true
          prerelease: true
          tag_name: ${{ github.sha }}
          name: ${{ github.sha }}
          body: |
            ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
